-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activity_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  location_id uuid NOT NULL,
  actor_name text NOT NULL,
  actor_image text,
  action text NOT NULL,
  entity_type text,
  entity_id text,
  details jsonb,
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  CONSTRAINT activity_log_pkey PRIMARY KEY (id),
  CONSTRAINT activity_log_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT activity_log_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id),
  CONSTRAINT activity_log_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.backhaul_order_lines (
  iso text NOT NULL,
  iso_line_number text NOT NULL,
  company_id uuid NOT NULL,
  location_id uuid NOT NULL,
  model text,
  serial text,
  acc_qty integer,
  line_status text,
  cancel text,
  confirm text,
  last_seen_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT backhaul_order_lines_pkey PRIMARY KEY (iso, iso_line_number, location_id)
);
CREATE TABLE public.backhaul_orders (
  iso text NOT NULL,
  iso_id text,
  company_id uuid NOT NULL,
  location_id uuid NOT NULL,
  inv_org text,
  start_date date,
  end_date date,
  backhaul_status text,
  cancel text,
  total_units integer,
  total_points integer,
  type text,
  sub_inventory text,
  adc text,
  scac text,
  is_open boolean NOT NULL DEFAULT true,
  last_seen_at timestamp with time zone NOT NULL DEFAULT now(),
  source text NOT NULL DEFAULT 'ge_dms_backhaul'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT backhaul_orders_pkey PRIMARY KEY (iso, location_id)
);
CREATE TABLE public.beacons (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  location_id uuid NOT NULL,
  name text NOT NULL,
  position_x numeric NOT NULL,
  position_y numeric NOT NULL,
  icon text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT beacons_pkey PRIMARY KEY (id),
  CONSTRAINT beacons_company_fk FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT beacons_location_fk FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.companies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  active boolean DEFAULT true,
  CONSTRAINT companies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.customers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  customer_name text NOT NULL,
  address text,
  phone text,
  email text,
  created_at timestamp with time zone DEFAULT now(),
  company_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  location_id uuid NOT NULL,
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_company_fk FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT customers_location_fk FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.deliveries (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  date date NOT NULL,
  truck_id text NOT NULL,
  stop integer NOT NULL,
  cso text NOT NULL,
  consumer_customer_name text NOT NULL,
  model text NOT NULL,
  qty integer NOT NULL DEFAULT 1,
  serial text,
  product_type text NOT NULL,
  status text NOT NULL DEFAULT 'PENDING'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  scanned boolean DEFAULT false,
  truck_fk uuid,
  customer_fk uuid,
  product_fk uuid,
  marked_for_truck boolean DEFAULT false,
  staged boolean DEFAULT false,
  company_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  location_id uuid NOT NULL,
  CONSTRAINT deliveries_pkey PRIMARY KEY (id),
  CONSTRAINT fk_deliveries_truck FOREIGN KEY (truck_fk) REFERENCES public.trucks(id),
  CONSTRAINT fk_deliveries_customer FOREIGN KEY (customer_fk) REFERENCES public.customers(id),
  CONSTRAINT fk_deliveries_product FOREIGN KEY (product_fk) REFERENCES public.products(id),
  CONSTRAINT deliveries_company_fk FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT deliveries_location_fk FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.floor_displays (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  location_id uuid NOT NULL,
  name text NOT NULL DEFAULT 'Floor Display'::text,
  pairing_code text NOT NULL UNIQUE,
  paired boolean NOT NULL DEFAULT false,
  state_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  last_heartbeat timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT floor_displays_pkey PRIMARY KEY (id),
  CONSTRAINT floor_displays_company_fk FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT floor_displays_location_fk FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.ge_changes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  location_id uuid NOT NULL,
  inventory_type text NOT NULL,
  serial text,
  model text,
  load_number text,
  cso text,
  change_type text NOT NULL,
  field_changed text,
  old_value text,
  new_value text,
  previous_state jsonb,
  current_state jsonb,
  source text NOT NULL,
  processed boolean DEFAULT false,
  processed_at timestamp with time zone,
  processed_action text,
  notes text,
  detected_at timestamp with time zone DEFAULT now(),
  inventory_bucket text,
  inventory_state text,
  source_type text,
  source_id uuid,
  CONSTRAINT ge_changes_pkey PRIMARY KEY (id),
  CONSTRAINT ge_changes_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT ge_changes_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.ge_inventory_source_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  location_id uuid NOT NULL,
  source_type text NOT NULL,
  inventory_bucket text,
  inventory_state text,
  serial text NOT NULL,
  model text,
  qty integer,
  cso text,
  sub_inventory text,
  ge_ordc text,
  ge_availability_status text,
  ge_availability_message text,
  ge_inv_qty integer,
  raw_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  last_seen_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ge_inventory_source_items_pkey PRIMARY KEY (id),
  CONSTRAINT ge_inventory_source_items_company_fk FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT ge_inventory_source_items_location_fk FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.inbound_receipt_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  location_id uuid NOT NULL,
  inbound_shipment_no text NOT NULL,
  line_index integer NOT NULL,
  cso text,
  tracking_number text,
  model text,
  serial text,
  inbound_replacement text,
  qty integer,
  rcvd integer,
  short integer,
  damage integer,
  serial_mix text,
  raw_line text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT inbound_receipt_items_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inbound_receipts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  location_id uuid NOT NULL,
  inbound_shipment_no text NOT NULL,
  scac text,
  truck_number text,
  scheduled_arrival_date text,
  scheduled_arrival_time text,
  actual_arrival_time text,
  total_units integer,
  total_pc_units integer,
  seal_number text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  summary_units integer,
  summary_points integer,
  asn_row_count integer,
  units_gap integer,
  CONSTRAINT inbound_receipts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inventory_conflicts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  location_id uuid NOT NULL,
  serial text NOT NULL,
  groups jsonb NOT NULL,
  source text,
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'resolved'::text])),
  detected_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventory_conflicts_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_conflicts_company_fk FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT inventory_conflicts_location_fk FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.inventory_conversions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  inventory_item_id uuid NOT NULL,
  from_inventory_type text NOT NULL,
  to_inventory_type text NOT NULL,
  from_sub_inventory text,
  to_sub_inventory text,
  converted_by text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  company_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  location_id uuid NOT NULL,
  CONSTRAINT inventory_conversions_pkey PRIMARY KEY (id),
  CONSTRAINT fk_conversion_item FOREIGN KEY (inventory_item_id) REFERENCES public.inventory_items(id),
  CONSTRAINT inventory_conversions_company_fk FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT inventory_conversions_location_fk FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.inventory_counts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  tracked_part_id uuid,
  qty integer NOT NULL,
  previous_qty integer,
  delta integer DEFAULT (qty - COALESCE(previous_qty, 0)),
  counted_by text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  count_reason text,
  company_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  location_id uuid NOT NULL,
  CONSTRAINT inventory_counts_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_counts_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT inventory_counts_tracked_part_id_fkey FOREIGN KEY (tracked_part_id) REFERENCES public.tracked_parts(id),
  CONSTRAINT inventory_counts_company_fk FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT inventory_counts_location_fk FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.inventory_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  date date,
  route_id text,
  stop integer,
  cso text NOT NULL,
  consumer_customer_name text,
  model text NOT NULL,
  qty integer DEFAULT 1,
  serial text,
  product_type text NOT NULL,
  status text,
  inventory_type text NOT NULL,
  sub_inventory text,
  is_scanned boolean DEFAULT false,
  scanned_at timestamp with time zone,
  scanned_by text,
  notes text,
  product_fk uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  company_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  location_id uuid NOT NULL,
  ge_availability_status text,
  ge_availability_message text,
  ge_ordc text,
  ge_model text,
  ge_serial text,
  ge_inv_qty integer,
  ge_orphaned boolean DEFAULT false,
  ge_orphaned_at timestamp with time zone,
  inventory_bucket text,
  inventory_state text,
  source_type text,
  source_id uuid,
  source_meta jsonb NOT NULL DEFAULT '{}'::jsonb,
  last_seen_at timestamp with time zone,
  CONSTRAINT inventory_items_pkey PRIMARY KEY (id),
  CONSTRAINT fk_inventory_product FOREIGN KEY (product_fk) REFERENCES public.products(id),
  CONSTRAINT inventory_items_company_fk FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT inventory_items_location_fk FOREIGN KEY (location_id) REFERENCES public.locations(id),
  CONSTRAINT inventory_items_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.ge_inventory_source_items(id)
);
CREATE TABLE public.load_conflicts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  location_id uuid NOT NULL,
  inventory_type text NOT NULL,
  load_number text NOT NULL,
  serial text NOT NULL,
  conflicting_load text NOT NULL,
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'resolved'::text])),
  notes text,
  detected_at timestamp with time zone DEFAULT now(),
  CONSTRAINT load_conflicts_pkey PRIMARY KEY (id),
  CONSTRAINT load_conflicts_company_fk FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT load_conflicts_location_fk FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.load_metadata (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  inventory_type text NOT NULL,
  sub_inventory_name text NOT NULL,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'staged'::text, 'in_transit'::text, 'delivered'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by text,
  notes text,
  category text,
  company_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  location_id uuid NOT NULL,
  friendly_name text,
  ge_source_status text,
  primary_color text,
  prep_tagged boolean DEFAULT false,
  prep_wrapped boolean DEFAULT false,
  pickup_date date,
  pickup_tba boolean DEFAULT false,
  ge_cso_status text,
  ge_inv_org text,
  ge_units integer,
  ge_submitted_date text,
  ge_cso text,
  ge_pricing text,
  ge_notes text,
  ge_scanned_at text,
  sanity_check_requested boolean DEFAULT false,
  sanity_check_requested_at timestamp with time zone,
  sanity_check_requested_by text,
  sanity_check_completed_at timestamp with time zone,
  sanity_check_completed_by text,
  items_scanned_count integer DEFAULT 0,
  items_total_count integer DEFAULT 0,
  scanning_complete boolean DEFAULT false,
  sanity_check_stage text CHECK (sanity_check_stage = ANY (ARRAY['early'::text, 'final'::text])),
  sanity_check_parameters jsonb,
  sanity_last_checked_at timestamp with time zone,
  sanity_last_checked_by text,
  CONSTRAINT load_metadata_pkey PRIMARY KEY (id),
  CONSTRAINT load_metadata_company_fk FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT load_metadata_location_fk FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.location_genesis_points (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  location_id uuid NOT NULL UNIQUE,
  genesis_lat numeric NOT NULL,
  genesis_lng numeric NOT NULL,
  genesis_scan_id uuid,
  established_at timestamp with time zone DEFAULT now(),
  established_by text,
  CONSTRAINT location_genesis_points_pkey PRIMARY KEY (id),
  CONSTRAINT location_genesis_points_location_fk FOREIGN KEY (location_id) REFERENCES public.locations(id),
  CONSTRAINT location_genesis_points_scan_fk FOREIGN KEY (genesis_scan_id) REFERENCES public.product_location_history(id)
);
CREATE TABLE public.locations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  slug text NOT NULL,
  name text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  active boolean DEFAULT true,
  CONSTRAINT locations_pkey PRIMARY KEY (id),
  CONSTRAINT locations_company_fk FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.order_deliveries (
  delivery_id text NOT NULL,
  cso text NOT NULL,
  company_id uuid NOT NULL,
  location_id uuid NOT NULL,
  delivery_status text,
  cso_type text,
  customer_po_number text,
  rap text,
  zip_group text,
  delivery_date date,
  delivery_name text,
  delivery_address_1 text,
  delivery_address_2 text,
  delivery_city text,
  delivery_state text,
  delivery_zip text,
  delivery_phone jsonb,
  last_updated_date timestamp with time zone,
  last_seen_at timestamp with time zone NOT NULL DEFAULT now(),
  source text NOT NULL DEFAULT 'ge_dms_orderdata'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT order_deliveries_pkey PRIMARY KEY (delivery_id, cso, location_id)
);
CREATE TABLE public.order_lines (
  cso text NOT NULL,
  delivery_id text NOT NULL,
  line_number text NOT NULL,
  company_id uuid NOT NULL,
  location_id uuid NOT NULL,
  line_status text,
  line_type text,
  item_type text,
  item text,
  product_type text,
  crated_indicator text,
  anti_tip_indicator text,
  product_weight integer,
  nmfc text,
  carton_code text,
  quantity integer,
  points numeric,
  shipment_number text,
  customer_tracking_number text,
  serials jsonb,
  last_seen_at timestamp with time zone NOT NULL DEFAULT now(),
  source text NOT NULL DEFAULT 'ge_dms_orderdata'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT order_lines_pkey PRIMARY KEY (cso, delivery_id, line_number, location_id)
);
CREATE TABLE public.orders (
  cso text NOT NULL,
  company_id uuid NOT NULL,
  location_id uuid NOT NULL,
  order_type text,
  order_date date,
  customer_name text,
  customer_account text,
  customer_phone text,
  freight_terms text,
  shipping_instructions text,
  shipping_method text,
  additional_service text,
  points numeric,
  last_seen_at timestamp with time zone NOT NULL DEFAULT now(),
  source text NOT NULL DEFAULT 'ge_dms_orderdata'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT orders_pkey PRIMARY KEY (cso, location_id)
);
CREATE TABLE public.product_location_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid NOT NULL,
  location_id uuid NOT NULL,
  product_id uuid,
  inventory_item_id uuid,
  scanning_session_id uuid,
  position_x numeric NOT NULL,
  position_y numeric NOT NULL,
  position_source text NOT NULL DEFAULT 'gps'::text CHECK (position_source = ANY (ARRAY['gps'::text, 'beacon'::text])),
  beacon_id uuid,
  raw_lat numeric,
  raw_lng numeric,
  accuracy numeric,
  scanned_by text,
  created_at timestamp with time zone DEFAULT now(),
  product_type text,
  sub_inventory text,
  CONSTRAINT product_location_history_pkey PRIMARY KEY (id),
  CONSTRAINT product_location_history_company_fk FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT product_location_history_location_fk FOREIGN KEY (location_id) REFERENCES public.locations(id),
  CONSTRAINT product_location_history_product_fk FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT product_location_history_session_fk FOREIGN KEY (scanning_session_id) REFERENCES public.scanning_sessions(id),
  CONSTRAINT product_location_history_beacon_fk FOREIGN KEY (beacon_id) REFERENCES public.beacons(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  model text NOT NULL UNIQUE,
  product_type text NOT NULL,
  brand text,
  description text,
  dimensions jsonb,
  created_at timestamp with time zone DEFAULT now(),
  image_url text,
  product_url text,
  price numeric,
  msrp numeric,
  color text,
  capacity text,
  availability text,
  commercial_category text,
  specs jsonb,
  updated_at timestamp with time zone DEFAULT now(),
  product_category text CHECK (product_category = ANY (ARRAY['appliance'::text, 'part'::text, 'accessory'::text])),
  is_part boolean DEFAULT false,
  CONSTRAINT products_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text,
  username text,
  image text,
  company_id uuid,
  role USER-DEFINED NOT NULL DEFAULT 'pending'::user_role,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.scanning_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  inventory_type text NOT NULL,
  sub_inventory text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'closed'::text])),
  scanned_item_ids ARRAY NOT NULL DEFAULT '{}'::uuid[],
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  closed_at timestamp with time zone,
  created_by text,
  updated_by text,
  closed_by text,
  company_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  location_id uuid NOT NULL,
  session_source text DEFAULT 'manual'::text CHECK (session_source = ANY (ARRAY['manual'::text, 'ge_sync'::text, 'system'::text])),
  CONSTRAINT scanning_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT scanning_sessions_company_fk FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT scanning_sessions_location_fk FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.settings (
  company_id uuid NOT NULL,
  sso_username text,
  sso_password text,
  updated_at timestamp with time zone DEFAULT now(),
  location_id uuid NOT NULL,
  ge_cookies jsonb,
  ge_cookies_updated_at timestamp with time zone,
  ui_handedness text DEFAULT 'right'::text,
  last_sync_asis_at timestamp with time zone,
  last_sync_fg_at timestamp with time zone,
  last_sync_sta_at timestamp with time zone,
  last_sync_inbound_at timestamp with time zone,
  last_sync_backhaul_at timestamp with time zone,
  last_sync_inventory_at timestamp with time zone,
  last_sync_orders_at timestamp with time zone,
  CONSTRAINT settings_pkey PRIMARY KEY (location_id),
  CONSTRAINT settings_company_fk FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT settings_location_fk FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.tracked_parts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  reorder_threshold integer NOT NULL DEFAULT 5,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by text,
  reordered_at timestamp with time zone,
  company_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  location_id uuid NOT NULL,
  CONSTRAINT tracked_parts_pkey PRIMARY KEY (id),
  CONSTRAINT tracked_parts_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT tracked_parts_company_fk FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT tracked_parts_location_fk FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.trucks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  truck_id text NOT NULL,
  driver_name text,
  capacity integer DEFAULT 50,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  abbreviated_name text UNIQUE,
  color text DEFAULT '#3B82F6'::text,
  company_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001'::uuid,
  location_id uuid NOT NULL,
  CONSTRAINT trucks_pkey PRIMARY KEY (id),
  CONSTRAINT trucks_company_fk FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT trucks_location_fk FOREIGN KEY (location_id) REFERENCES public.locations(id)
);
CREATE TABLE public.user_agent_keys (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  provider text NOT NULL CHECK (provider = ANY (ARRAY['openai'::text, 'anthropic'::text, 'groq'::text, 'gemini'::text])),
  api_key text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_agent_keys_pkey PRIMARY KEY (id),
  CONSTRAINT user_agent_keys_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);